[info]
display_name = "Euclid" # ingame display name
author = "Jean Du Plessis"
version = "0.0.1"
description = "A simple map featuring a simple platform"
keywords = ["char"] # keywords to find the map in search
base_dimensions = [1280, 720]
icon = "char/Euclid/coreone.png"

[core]
asset = "coreone"
character_assets = ["coreone", "coretwo","corethree","corefour"]
rotation = 0.0
origin = [0.0, 0.0, 1.0]
scale = [0.23,0.23,0.23]
physobj_id = "core"

[[char_component]]
asset = "facehole"
rotation = 0.0
origin = [0.0, 0.0, 5.0]
scale = [0.23,0.23,0.23]
physobj_id = "core"
enable_sync_rotation = false
face_dir_looking_radius = 6.0

[[asset.svg]]
name = "coreone"
path = "coreone.svg"

[[asset.svg]]
name = "coretwo"
path = "coretwo.svg"

[[asset.svg]]
name = "corethree"
path = "corethree.svg"

[[asset.svg]]
name = "corefour"
path = "corefour.svg"

[[asset.svg]]
name="leftswordsvg"
path = "sword.svg"

[[collider.convex]]
id = "sword"
points = [[-19, 98], [17,73], [-19, -65], [17,-65]]
indices = [[0, 1], [1, 3], [3, 2], [2, 0]]
origin = [0.0, 0.0, 300.0]

[[collider.convex]]
id = "sword2"
points = [[-19, 98], [17,98], [-19, -65], [17,-40]]
indices = [[0, 1], [1, 3], [3, 2], [2, 0]]
origin = [0.0, 0.0, 300.0]


[[physics_object]]
id = "swordheavy"
collider_ids = ["sword"]

[[physics_object]]
id = "swordheavy2"
collider_ids = ["sword2"]

[[asset.svg]]
name = "facehole"
path = "face.svg"

[[asset.svg]]
name="limb"
path="t1.svg"

[[physics_object]]
id = "core"
linear_damping = 0.4
angular_damping = 4.0
collider_ids = ["core", "core_jump_reset"]

[collider.jump_reset_colliders]
colliders = ["core_jump_reset"]

[velocity_cap]
max_velocity = [100.0, 5000.0]
max_external_force = [600.0, 5000.0]
max_angvel = 5.467
#pub max_velocity: Option<[f32;2]>,
#pub max_angvel: Option<f32>,
#pub max_external_force: Option<[f32;2]>,
#pub max_external_torque: Option<f32>,

[[collider.circle]]
id = "core"
radius = 19.0
fricoeff = 1.0

[[collider.circle]]
id = "core_jump_reset"
radius = 25.0
fricoeff = 1.0

[char_movement_action.pressed_up]
set_velocity = [0.0, 700.0]
require_available_jumps = true

[char_movement_action.pressed_left]
add_external_force = [-600.0, 0.0]

[char_movement_action.pressed_right]
add_external_force = [600.0, 0.0]

[char_movement_action.unpressed_left]
add_external_force = [600.0, 0.0]

[char_movement_action.unpressed_right]
add_external_force = [-600.0, 0.0]

[health]
maximum_health = 1000.0
healthbar_distance = 36.2
width = 50.0
height = 6.0
radius = 3.0
subdivisions = 3

[text_identifier]
distance = 55.2
size = 26.6

[player_descriptor]
maximum_jumps = 1

[attack_identifier]
distance = 36.2
size = 18.3

[[projectile]]
id = "left_sword_stab"
asset = "leftswordsvg"
scale = [0.10,0.10, 1.0]
spawn_z_axis = 700.0
physobj_id = "swordheavy"
spawn_origin_looking_radius = 130.0
rotation = 1.57079633
lifetime = 0.6
damage = 150


[[projectile]]
id = "none_sword_stab"
asset = "leftswordsvg"
scale = [0.10,0.10, 1.0]
spawn_z_axis = 700.0
physobj_id = "swordheavy"
spawn_origin_looking_radius = 0.0
rotation = 0.0
lifetime = 0.6
damage = 150

[[projectile]]
id = "up_left_sword_stab"
asset = "leftswordsvg"
scale = [0.10,0.10, 1.0]
spawn_z_axis = 700.0
physobj_id = "swordheavy"
spawn_origin_looking_radius = 130.0
rotation = 0.78539816
lifetime = 0.6
damage = 150


[[projectile]]
id = "down_left_sword_stab"
asset = "leftswordsvg"
scale = [0.10,0.10, 1.0]
spawn_z_axis = 700.0
physobj_id = "swordheavy"
spawn_origin_looking_radius = 130.0
rotation = 2.35619449
lifetime = 0.6
damage = 150


[[projectile]]
id = "up_sword_stab"
asset = "leftswordsvg"
scale = [0.10,0.10, 1.0]
spawn_z_axis = 700.0
physobj_id = "swordheavy"
spawn_origin_looking_radius = 130.0
rotation = 0.0
lifetime = 0.6
damage = 150

[[projectile]]
id = "down_sword_stab"
asset = "leftswordsvg"
scale = [0.10,0.10, 1.0]
spawn_z_axis = 700.0
physobj_id = "swordheavy"
spawn_origin_looking_radius = 130.0
rotation = 3.14159265
lifetime = 0.6
damage = 150

[[projectile]]
id = "down_right_sword_stab"
asset = "leftswordsvg"
scale = [0.10,-0.10, 1.0]
spawn_z_axis = 700.0
sync_offset=[-24,24,0]
physobj_id = "swordheavy2"
spawn_origin_looking_radius = 165.0
rotation = 0.78539816
lifetime = 0.6
damage = 150

[[projectile]]
id = "up_right_sword_stab"
asset = "leftswordsvg"
scale = [-0.10,0.10, 1.0]
spawn_z_axis = 700.0
physobj_id = "swordheavy"
spawn_origin_looking_radius = 130.0
rotation = -0.7853982
lifetime = 0.6
damage = 150

[[projectile]]
id = "right_sword_stab"
asset = "leftswordsvg"
scale = [0.10,-0.10, 1.0]
sync_offset=[-35,0,0]
spawn_z_axis = 700.0
physobj_id ="swordheavy2"
spawn_origin_looking_radius = 165.0
rotation = 1.57079633
lifetime = 0.6
damage = 150

[[movement_action]]
id= "stab_left"
instance_affected_id = "stab"
set_velocity = [-600.0, 0.0]

[[movement_action]]
id= "stab_down"
instance_affected_id = "stab"
set_velocity = [0.0, -600.0]

[[movement_action]]
id= "stab_up"
instance_affected_id = "stab"
set_velocity = [0.0, 600.0]

[[movement_action]]
id= "stab_up_left"
instance_affected_id = "stab"
set_velocity = [-424.264069, 424.264069]

[[movement_action]]
id= "stab_up_right"
instance_affected_id = "stab"
set_velocity = [424.264069, 424.264069]

[[movement_action]]
id= "stab_down_right"
instance_affected_id = "stab"
set_velocity = [424.264069, -424.264069]

[[movement_action]]
id= "stab_down_left"
instance_affected_id = "stab"
set_velocity = [-424.264069, -424.264069]

[[movement_action]]
id= "stab_right"
instance_affected_id = "stab"
set_velocity = [600.0, 0.0]

[[movement_attack_action]]
id = "stab_attack"
left_id = "stab_left"
right_id = "stab_right"
down_id = "stab_down"
up_eid = "stab_up"
none_id = "stab_up"
up_left_id = "stab_up_left"
up_right_id = "stab_up_right"
down_left_id = "stab_down_left"
down_right_id = "stab_down_right"


[[spawn_projectile_action]]
id = "sword_stab"
left_id = "left_sword_stab"
up_id = "up_sword_stab"
none_id = "none_sword_stab"
right_id = "right_sword_stab"
instance_id = "stab"
down_id = "down_sword_stab"
up_left_id = "up_left_sword_stab"
up_right_id = "up_right_sword_stab"
down_left_id = "down_left_sword_stab"
down_right_id = "down_right_sword_stab"

[attack.one_one]
actions = ["sword_stab", "stab_attack"]
cooldown = 0.59